# Generated by Django 4.2.2 on 2023-06-21 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_customer_product_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='catgory',
            new_name='category',
        ),
    ]
