# Generated by Django 4.2.2 on 2023-06-21 16:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_order_status_alter_customer_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_ordered',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
